Tweaks to visibility logic for admin toolbar edit button
dof-dss/nidirect-site-modules pull request #350
Opened 2021-03-12 15:59 UTC by neilblair

This PR tweaks the logic for showing the admin toolbar Edit button so that is available to editors:
- when using the layout builder on a landing page
- on the homepage so that they easily edit features.

2021-03-14 09:01 UTC, omahm commented on nidirect_common/nidirect_common.module
> +    $current_alias = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
path.alias_manager is deprecated and should be replaced with path_alias.manager

2021-03-14 09:01 UTC, omahm requested changes
LG, just need to replace the deprecated service.

2021-03-15 11:04 UTC, omahm approved these changes
LG 👍

2021-03-15 14:32 UTC, DuttonMa approved these changes

2021-03-18 21:56 UTC, merged